title: EASTER
theme: null  # disable GitHubâ€™s default theme
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
defaults:
  - scope: { path: "", type: "pages" }
    values: { layout: default }
